{{-- resources/views/exports/data-libur-nasional-pdf.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Data Libur Nasional</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
            line-height: 1.4;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        .header h2 {
            margin: 5px 0 0 0;
            font-size: 14px;
            color: #666;
            font-weight: normal;
        }
        
        .info {
            margin-bottom: 20px;
            font-size: 11px;
            color: #666;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        
        table th {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            padding: 10px 8px;
            text-align: center;
            font-weight: bold;
            color: #333;
            font-size: 11px;
        }
        
        table td {
            border: 1px solid #dee2e6;
            padding: 8px;
            font-size: 11px;
            vertical-align: top;
        }
        
        table tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        
        table tr:hover {
            background-color: #e9ecef;
        }
        
        .text-center {
            text-align: center;
        }
        
        .text-right {
            text-align: right;
        }
        
        .footer {
            margin-top: 30px;
            border-top: 1px solid #dee2e6;
            padding-top: 15px;
            font-size: 10px;
            color: #666;
        }
        
        .total-records {
            background-color: #e3f2fd;
            font-weight: bold;
            color: #1976d2;
        }
        
        @page {
            margin: 15mm;
            @bottom-right {
                content: "Halaman " counter(page) " dari " counter(pages);
                font-size: 10px;
                color: #666;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Data Libur Nasional</h1>
        <h2>Laporan Lengkap</h2>
    </div>
    
    <div class="info">
        <strong>Tanggal Export:</strong> {{ date('d/m/Y H:i:s') }}<br>
        <strong>Total Data:</strong> {{ $data->count() }} records
    </div>
    
    <table>
        <thead>
            <tr>
                <th style="width: 8%;">No</th>
                <th style="width: 22%;">Tanggal</th>
                <th style="width: 70%;">Keterangan</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $index => $item)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td class="text-center">{{ \Carbon\Carbon::parse($item->tanggal)->format('d/m/Y') }}</td>
                <td>{{ $item->keterangan }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="3" class="text-center" style="padding: 20px; color: #999;">
                    Tidak ada data untuk ditampilkan
                </td>
            </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr class="total-records">
                <td colspan="2" class="text-center"><strong>Total Records</strong></td>
                <td class="text-center"><strong>{{ $data->count() }}</strong></td>
            </tr>
        </tfoot>
    </table>
    
    <div class="footer">
        <div style="float: left;">
            <strong>Generated by:</strong> Your Application Name<br>
            <strong>System:</strong> Data Management System
        </div>
        <div style="float: right;">
            <strong>Export Date:</strong> {{ date('d F Y') }}<br>
            <strong>Time:</strong> {{ date('H:i:s') }} WIB
        </div>
        <div style="clear: both;"></div>
    </div>
</body>
</html>